spring:
  datasource:
    url: jdbc:mysql://localhost:3306/satal-technologies?createDatabaseIfNotExist=true
    username: root
    password: 6830
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      indent-output: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 6880
  servlet:
    context-path: /technologies
